export const EMPLOYEE_LIST = 'EMPLOYEE_LIST';
export const SET_EMPLOYEE_LIST = 'SET_EMPLOYEE_LIST';
export const GET_EMPLOYEE_LIST = 'GET_EMPLOYEE_LIST';
export const SET_EMPLOYEE = 'SET_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE';
export const SAVE_EMPLOYEE = 'SAVE_EMPLOYEE';